# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'furryoctoninja' do
    pod 'Alamofire', '1.3.1'
    pod 'SwiftyJSON', '~> 2.2.1'
    pod 'Locksmith'
end

target 'furryoctoninjaTests' do

end
